#!/bin/sh

PDFOpen () {
    [ -n "$ref" ] && ${BIB_OPENER:-xdg-open} "$BIB_PDF_PATH/$ref.pdf" || NotiPrompt "$cite.pdf does not exist"
}

OpenBIB () {
    # Usage: OpenBIB
    # Input: $criterion
    # Output: Open pdf files
    case "$criterion" in
	"title")
	    bibtexgen "/$cite/"
	    PDFOpen
	    ;;
	"authoryear")
	    cite_author="${cite%% --- *}"
	    cite_year="${cite##* --- }"
	    bibtexgen "/$cite_author/ && /$cite_year/"
	    PDFOpen
	    ;;
	"mixed")
	    cite_title="${cite##* --- }"
	    bibtexgen "/$cite_title/"
	    PDFOpen
	    ;;
    esac
}

# NoteOpen () {
#     note="$BIB_NOTE_PATH/$ref.md"
#     [ ! -f "$note" ] &&
# 	title="$(printf '%s' "$bibtex" | grep -i "title.*" | sed "s/^.*title \?= \?{\?//g; s/}\?,\?$//g")" &&
# 	author="$(printf '%s' "$bibtex" | grep -i "author.*" | sed "s/^.*author \?= \?{\?//g; s/}\?,\?$//g")" &&
# 	printf '%s\n\n' "# $title" "Author: $author" > "$note"
#     mimetype=$(xdg-mime query filetype "$note")
#     appdesktop=$(xdg-mime query default "$mimetype")
#     grep -q "Terminal=false" < "$(find "$XDGDIR1" "$XDGDIR2" -name "$appdesktop" | tail -n 1)" &&
# 	${BIB_OPENER:-xdg-open} "$note" ||
# 	$TERMINAL -e "${BIB_OPENER:-xdg-open}" "$note"
# }

NoteOpen () {
    note="$BIB_NOTE_PATH/$ref/$ref.tex"
    [ ! -f "$note" ] &&
	title="$(printf '%s' "$bibtex" | grep -i "title.*" | sed "s/^.*title \?= \?{\?//g; s/}\?,\?$//g")" &&
	author="$(printf '%s' "$bibtex" | grep -i "author.*" | sed "s/^.*author \?= \?{\?//g; s/}\?,\?$//g")" &&
	mkdir -p "$BIB_NOTE_PATH/$ref/" &&
	printf '%s\n' \
	    '\documentclass[a4paper]{article}' \
	    '\usepackage[utf8]{inputenc}' \
	    '\usepackage[T1]{fontenc}' \
	    '\usepackage{textcomp}' \
	    '\usepackage{amsmath, amssymb, amsthm}' \
	    '\usepackage{import}' \
	    '\usepackage{pdfpages}' \
	    '\usepackage{transparent}' \
	    '\usepackage{xcolor}' \
	    '\newcommand{\inkfig}[2][1]{%' \
	    '    \def\svgwidth{#1\columnwidth}' \
	    '    \import{./figures/}{#2.pdf_tex}' \
	    '}' \
	    '\pdfsuppresswarningpagegroup=1' \
	    "\\title{Hui-Jun Chen's Note on \"$title\"}" \
	    "\\author{Author(s): $author}" \
	    '\date{\today}' \
	    '\begin{document}' \
	    '\maketitle' \
	    '' \
	    '' \
	    '' \
	    '\end{document}' > "$note"
    mimetype=$(file --mime-type -b "$note" 2>/dev/null)
    case "$mimetype" in
	text/*|*x-empty*|*json*)
	    case "$TERMINAL" in
		"") ${BIB_OPENER:-xdg-open} "$note" ;;
		*) $TERMINAL -e "${EDITOR:-vi}" "$note" ;;
	    esac
	    ;;
	*) ${BIB_OPENER:-xdg-open} "$note" ;;
    esac
}

NoteBIB () {
    # Usage: NoteBIB
    # Input: $criterion
    # Output: Open Note file
    case "$criterion" in
	"title")
	    bibtexgen "/$cite/"
	    [ -n "$ref" ] && NoteOpen
	    ;;
	"authoryear")
	    cite_author="${cite%% --- *}"
	    cite_year="${cite##* --- }"
	    bibtexgen "/$cite_author/ && /$cite_year/"
	    [ -n "$ref" ] && NoteOpen
	    ;;
	"mixed")
	    cite_title="${cite##* --- }"
	    bibtexgen "/$cite_title/"
	    [ -n "$ref" ] && NoteOpen
	    ;;
    esac
}
